version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Building, Testing, and packaging the application..."
      - sh mvnw package -DskipTests  # Use 'sh' to execute
      - echo "Listing contents of target directory..."
      - ls target/

  post_build:
    commands:
      - echo "Build, Testing, and packaging completed."
      - echo "Checking if JAR file is created..."
      - ls target/

artifacts:
  files:
    - '**/target/*.jar'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
